emil-e/rapidcheck

src/detail/Configuration.cpp, src/detail/Testing.cpp, src/detail/Utility.cpp
It causes errors when I try to compile the library.
I'm trying to pick up the GC stuff I worked on before, and I have more or less given up the idea of writing GC'd code in C++ for testing. In order to support copying garbage collectors, the test programs must be written so that on every GC safepoint (in my simple case allocations) there must be no raw pointers to objects (for example this or by-ref params), and that just doesn't work out. So I'm going to try to generate mutator programs and use the stateful testing capabilities of RapidCheck instead. Curious to see how that turns out.
=> Remove some unused code

doc/assertions.md, include/rapidcheck/Assertions.h, include/rapidcheck/Assertions.hpp, src/detail/Assertions.cpp, test/AssertionsTests.cpp, test/detail/Base64Tests.cpp, test/detail/SerializationTests/CompactIntegers.cpp, test/detail/SerializationTests/CompactRanges.cpp, test/detail/SerializationTests/Misc.cpp, test/gen/ContainerTests/Fixed.cpp, test/gen/NumericTests.cpp, test/gen/PredicateTests.cpp, test/gen/detail/ExecRawTests.cpp, test/util/Serialization.h
Took the naming convention (THROWS and THROWS_AS) from Catch.
=> Add exception checking macros

include/rapidcheck/Show.hpp, include/rapidcheck/detail/BitStream.hpp, include/rapidcheck/detail/ShowType.hpp, include/rapidcheck/detail/TestListenerAdapter.h, include/rapidcheck/detail/Utility.h, include/rapidcheck/fn/Common.hpp, include/rapidcheck/gen/Tuple.hpp, src/detail/LogTestListener.cpp, src/detail/PropertyContext.cpp, src/gen/Numeric.cpp, src/gen/detail/GenerationHandler.cpp
Very trivial changes to silence gcc warnings about unused parameters.
=> Fix warnings about unused parameters.

src/detail/Platform.cpp
Allow building with clang 4.0 compiler under Windows.
Remove unused variables (cmake file has /WX - warnings are errors) and
make explicit in one stage of a 2 stage type conversion (char* -> std::string ->
Maybe) all in one function.
=> let clang build on Windows

include/rapidcheck/detail/BitStream.hpp, include/rapidcheck/detail/Utility.h, test/detail/BitStreamTests.cpp
Using GCC 6.3.1 and the `-fsanitize=address,undefined` compile flags, a project I've been testing using RapidCheck has been throwing the below failures (NB. the paths are munged to be more readable),
```
./include/rapidcheck/detail/BitStream.hpp:60:12: runtime error: shift exponent 64 is too large for 64-bit type 'uint64_t' (aka 'unsigned long')
SUMMARY: AddressSanitizer: undefined-behavior ./include/rapidcheck/detail/BitStream.hpp:60:12
```
```
./include/rapidcheck/detail/Utility.h:98:37: runtime error: left shift of negative value -2
SUMMARY: AddressSanitizer: undefined-behavior ./include/rapidcheck/detail/Utility.h:98:37
```
This PR aims to avoid these undefined bit-shift behaviors and -- in admittedly very loose, "Does it work on my machine?" tests -- seems to do the job.
=> Avoid undefined behavior

CMakeLists.txt
This removes warnings when using CMake >= 3.3 if you have symbol visibility set.
Or you could change the minimum version to 3.3. There are only 6 policy changes since then and it is now 2 years old. Ubuntu 16.04 LTS has CMake 3.5 for comparison.
No doubt Debian Stable has some ancient version but they love that. :-)
=> Use NEW settings for CMP0063 policy

extras/boost_test/include/rapidcheck/boost_test.h, include/rapidcheck/Gen.hpp
There were a few annoying warnings (both compiler and runtime) when using VS2015 and Boost.Test:
- When RapidCheck tests passed Boost.Test would report that the test had no assertions
- When compiling with Boost.Test integration there was a warning about unused parameters
- When compiling on VS2015 there was a warning about unreachable code
=> Warning fixes when using Boost.Test and VS2015

include/rapidcheck/gen/Maybe.hpp, include/rapidcheck/shrink/Shrink.hpp, src/detail/Platform.cpp, src/detail/Results.cpp, test/CheckTests.cpp, test/GenTests.cpp, test/RandomTests.cpp, test/SeqTests.cpp, test/ShrinkableTests.cpp, test/detail/ApplyTupleTests.cpp, test/detail/BitStreamTests.cpp, test/detail/ImplicitParamTests.cpp, test/detail/LogTestListenerTests.cpp, test/detail/PropertyTests.cpp, test/detail/SerializationTests/Misc.cpp, test/detail/TestingTests.cpp, test/detail/VariantTests.cpp, test/gen/NumericTests.cpp, test/gen/detail/ExecRawTests.cpp, test/shrink/ShrinkTests.cpp, test/shrinkable/CreateTests.cpp, test/shrinkable/OperationsTests.cpp, test/shrinkable/TransformTests.cpp, test/state/gen/CommandsTests.cpp, test/state/gen/ExecCommandsTests.cpp, test/util/Generators.h, test/util/IntVec.h, test/util/ThrowOnCopy.h
Bunch of small fixes. Feel free to cherry-pick specific commits if you don't want it all.
This allows for compilation with clang 5's options:
`-Weverything -Wno-c++98-compat -Wno-padded -Wno-weak-vtables -Wno-c++98-compat-pedantic -Wno-deprecated -Wno-documentation-unknown-command -Wno-global-constructors -Wno-exit-time-destructors -Wno-sign-conversion -Wno-conversion -Wno-float-equal -Wno-inconsistent-missing-destructor-override -Wno-unused-parameter -Wno-gnu-zero-variadic-macro-arguments`, but to do so it may require https://github.com/emil-e/rapidcheck/pull/167 first.
=> Various fixes

ext/get_boost.sh
This fixes one issue about invalid use of placement new: https://lists.boost.org/Archives/boost/2016/04/228755.php https://github.com/boostorg/function/pull/9
=> Update boost to 1.65.1

include/rapidcheck/Assertions.h
To help CLion's syntax checker.
=> chore: Explicitly specify namespace

CMakeLists.txt
This skips any C-compiler-related checks
=> Mark CMake project as pure C++

include/rapidcheck/detail/Utility.h
bitwise `~` promotes smaller integral types to `int`. This patch is supposed to fix the warning.
=> Fix left shift of negative value caused by integral promotion

CMakeLists.txt, src/detail/Configuration.cpp
I have noticed that when compiling and running tests that use RapidCheck on Windows with MSYS2 and MinGW, the same random seed is used every time. This seems to be a flaw in the underlying stdlib, `std::random_device` always returns the same value, making it useless as a seed.
I have implemented a workaround to instead use the system time as the random seed when compiled with MinGW.
I found this relevant post on StackOverflow: https://stackoverflow.com/questions/18880654/why-do-i-get-the-same-sequence-for-every-run-with-stdrandom-device-with-mingw
=> Use system time as the random seed when compiled with MinGW

CMakeLists.txt
Without the `-stdlib=libc++` option the build fails with:
[  5%] Building CXX object CMakeFiles/rapidcheck.dir/src/Check.cpp.o
In file included from /Users/yairchu/dev/rapidcheck/src/Check.cpp:1:
In file included from /Users/yairchu/dev/rapidcheck/include/rapidcheck/Check.h:21:
In file included from /Users/yairchu/dev/rapidcheck/include/rapidcheck/Check.hpp:5:
/Users/yairchu/dev/rapidcheck/include/rapidcheck/detail/Configuration.h:3:10: fatal error: 'cstdint' file not found
=> fix build on macOS

test/GenTests.cpp, test/MaybeTests.cpp, test/SeqTests.cpp, test/ShrinkableTests.cpp, test/detail/VariantTests.cpp, test/state/gen/ExecCommandsTests.cpp
Because RapidCheck builds with the werror flag, warnings appearing with newer compilers might cause some issues. It is possible to hit this when building with clang 8. The error -Wself-assign-overloaded is
reported in some of the test cases for the project, which actually  test for self-assignment. To continue building with no warnings, we can add a small indirection where we just take a local reference and perform the self-assignment using it. This reduces the need to use pragmas or the need to modify the with warning flags for the test files.
Additionally, a deprecation warning is reported in ExecCommandsTests.cpp because a pragma that disables the warning locally is used only when compiling with gcc. That check should be extended to also handle clang since the same code works for clang …
=> Fix warnings when compiling with clang 8

CMakeLists.txt, extras/CMakeLists.txt, extras/boost/CMakeLists.txt, extras/boost_test/CMakeLists.txt, extras/catch/CMakeLists.txt, extras/gmock/CMakeLists.txt, extras/gtest/CMakeLists.txt
There are a couple of improvements made to the CMake files in order to make the export and import of the CMake targets more useful and, in general, make the library be as easily consumed as an external dependency as it is including it as sub-project - if RapidCheck is to be used in different package managers, this is essential.
The changes were motivated by the desire to add a port of RapidCheck to VCPKG (a C++ based package manager). Here is a description of the major changes:
- The install interface directories were not properly set, leading to the need to use "../rapidcheck.h" to access the primary library header. The fix for this is trivial.
- All the extra integration header-only libraries are now properly installed and exported so that these integration can now be used from an …
=> Improve CMake installation

doc/generators_ref.md, include/rapidcheck/gen/Container.hpp, test/gen/ContainerTests/Unique.cpp
I've run into the need to generate fixed-size containers with unique elements (for generating valid CSR matrices); this PR adds the functionality into rapidcheck as additional overloads for `gen::unique` and `gen::uniqueBy`, similar to what's already there for `gen::container`.
=> Add fixed-count overloads for gen::unique(By)

include/rapidcheck/Random.h, include/rapidcheck/detail/BitStream.hpp
Random was using `std::ostream` without `<iosfwd>` and `std::hash`
without `<functional>`. In BitStream.hpp, if `SourceType` was unsigned
then the comparison to `numBits` (which returns `signed int`) would
cause a warning (which makes the code not compile because the
CMakeLists.txt sets -Werror on gcc/clang).
On a related note, `numBits` should probably be some unsigned type, and the `CMakeLists.txt` should _not_ set `-Werror` by default (otherwise the code will suddenly start failing to compile whenever you upgrade to a smarter compiler, which is all well and good if you're developing the library but it's a nightmare for package maintainers and consumers).
=> Add missing includes and fix signed/unsigned comparison

CMakeLists.txt
This PR is intended to fix issue #247.
I am a bit unhappy about the fact that the compile definitions has to be declared as `PUBLIC` in CMake, meaning that it will propagate to all the projects that link to Rapidcheck. An alternative way to solve the bug would be to remove any appearance of the `RC_USE_RTTI` symbol from header files and move them to the implementation. If we do that, `RC_USE_RTTI` will become a `PRIVATE` symbol (like `RC_SEED_SYSTEM_TIME`).
=> CMake: use `target_compile_definitions()` for the `RC_USE_RTTI` symbol

include/rapidcheck/gen/Numeric.hpp
Avoid warning by using explicit casting to double
`../include/rapidcheck/gen/Numeric.hpp:46:43: warning: implicit conversion from 'std::__1::numeric_limits<unsigned long long>::type' (aka 'unsigned long long') to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-int-float-conversion]`
```
(stream.next<uint64_t>() * scale) / std::numeric_limits<uint64_t>::max();
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Fixes #252
=> Numeric: Fix Wimplicit-int-float-conversion with clang-10

include/rapidcheck/Assertions.h
As per GCC's error message: ISO C++11 requires at least one argument for
the "..." in a variadic macro. This can be noticed if compiling with
-pedantic, producing a warning. If -Werror is added, it becomes an
error. This PR adds a dummy last argument in all cases using the
RC_INTERNAL_CONDITIONAL_RESULT macro without one.
Tested on GCC 7.4.0 and Clang 6.0.0 .
=> Add argument for "..." in variadic assert macros

include/rapidcheck/gen/Arbitrary.h, include/rapidcheck/gen/Arbitrary.hpp
Added optional second type to `rc::Arbitrary` template to support single-type template specializations of `rc::Arbitrary` that use SFINAE patterns like `std::enable_if` to determine which one to choose.  It modifies the signature to be `template <typename T, typename=void> struct Arbitrary;`.
All existing `rapidcheck` unit tests passed with the change, which is 25 characters of total addition.  I don't see any explicit tests for `Arbitrary` anywhere so I wasn't sure if I should add anything to the tests.  I am assuming that it is implicitly tested quite well because it's fundamental to rapidcheck's data generation scheme, which is well tested.
For a little background and justification: I'm using rapidcheck in a project at $DAY_JOB to generate templated objects.  I want to optionally …
=> SFINAE support for `Arbitrary` struct

CMakeLists.txt, include/rapidcheck/detail/Any.hpp, include/rapidcheck/detail/ShowType.hpp, include/rapidcheck/state/Command.hpp, test/detail/ShowTypeTests.cpp, test/state/gen/ExecCommandsTests.cpp
Changed RC_USE_RTTI to RC_DONT_USE_RTTI and changed associated `#ifdef`s to `#ifndef`.
This PR is to solve #267 using suggested solution 1.  It's not backwards compatible, so I expect it will cause some breakage in some other projects if they are disabling RTTI in their environments.
=> Inverted logic of rtti enablement.

include/rapidcheck/Compat.hpp
Alias `rc::compat::return_type` to `std::result_of` for C++14 and earlier, instead of C++17 and earlier as it used to be.
The reason is that `std::result_of`, while still available in C++17, is deprecated and may result in warnings, for example warning STL4014 in Visual Studio 2017:
```
c:\project\thirdparty\rapidcheck\include\rapidcheck\compat.hpp(10): error C4996: 'std::result_of<_Callable(_Args...)>': warning STL4014: std::result_of and std::result_of_t are deprecated in C++17. They are superseded by std::invoke_result and std::invoke_result_t. You can define _SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```
=> Fix rc::compat::return_type definition warning

include/rapidcheck/gen/Container.hpp
GCC emits a deprecated warning when 'this' is implicitly captured by
value. Change the lambdas that were implicitly capturing to an explicit
capture.
=> Remove implicit capture of this

ext/get_boost.sh
The CI was failing in #275 because of a broken download link. This PR changes the URL to what is provided at https://www.boost.org/users/download/
The Boost version is not changed.
=> boost: Update URL to download Boost

extras/boost_test/include/rapidcheck/boost_test.h
Without this, compilation fails if `rapidcheck/boost_test.h` is included before `boost/test/unit_test.h`.
=> boost_test: Add missing include for BOOST_CHECK, BOOST_FAIL

include/rapidcheck/gen/detail/ShrinkValueIterator.hpp, include/rapidcheck/seq/SeqIterator.h
Using `std::iterator` as a base class has been deprecated since C++17, so this replaces it with the member types that it would define.
While I've done this change with C++17 in mind, this should be a fully-backwards compatible change with previous C++ standards.
=> Remove the use of the deprecated `std::iterator`

CMakeLists.txt, include/rapidcheck/Compat.hpp
The fix for `std::result_of` being removed in C++20 checks `__cplusplus`, which isn't always set in MSVC, which also happens to be the compiler that removed `std::result_of`, so it adds `/Zc:__cplusplus` to the command line to fix this. This creates another problem however: When using the package in Clang, which doesn't support `/Zc:__cplusplus`, you get an error and it doesn't work. This is a problem for [vcpkg#22100](https://github.com/microsoft/vcpkg/pull/22100).
The solution is to use the feature test macro `__cpp_lib_is_invocable` instead, which tests exactly what we want to know.
=> Use `__cpp_lib_is_invocable` instead of `__cplusplus`.

test/seq/TransformTests.cpp
With moves towards inclusive language:
https://www.ibm.com/blogs/think/2020/08/words-matter-driving-thoughtful-change-toward-inclusive-language-in-technology/
we'd like to contribute the changes shown in this PR back to the community for greater acceptance. The particular reason for this 
change is sanity is becoming an offensive word towards neurodiverse individuals.
=> Updates for inclusive language

include/rapidcheck/detail/BitStream.h, include/rapidcheck/detail/BitStream.hpp
Fixes #289
Prior to this, calling `nextWithSize(kNominalSize + 1)` would result in a
call like `next<std::int64_t>(65)`. This lead to undefined behaviour in a
bit shift like `value |= (bits << 65)`. Calls such as this may happen
during testing as the size grows while trying to find problem cases.
=> Fix undefined behaviour in BitStream::nextWithSize

extras/catch/include/rapidcheck/catch.h, test/detail/BitStreamTests.cpp
With the official release of [Catch2 v3.0.1](https://github.com/catchorg/Catch2/releases/tag/v3.0.1) the header structure of that library has changed, and this breaks compatibility with anyone including `<rapidcheck/catch.h>`, since it includes the old header.
The fix I've added is to not do anything if the user has already included the new `<catch2/catch_test_macros.hpp>` header. This should be compatible with any code that stays on v2.x versions of Catch2, and also compatible with anyone using the new major version of Catch2, with minor modifications, which they will have to make anyway when switching.
This does not touch any of RapidCheck's tests. The reason for this is Catch2 v3 is a C++14 library, and RapidCheck is currently a C++11 library.
Another change this pull request makes is …
=> Very basic support for Catch2 v3

include/rapidcheck/detail/Serialization.hpp, include/rapidcheck/detail/Utility.h, src/detail/Base64.h
`std::uint8_t` and friends are defined in `<cstdint>` header. Without the change `rapidcheck` build fails on weekly `gcc-13` snapshot as:
In file included from /build/source/src/detail/Base64.cpp:1:
/build/source/src/detail/Base64.h:13:49: error: 'uint8_t' is not a member of 'std'; did you mean 'wint_t'?
13 | std::string base64Encode(const std::vector<std::uint8_t> &data);
|                                                 ^~~~~~~
=> add missing <cstdint> includes exposed by gcc-13

doc/doctest.md, extras/CMakeLists.txt, extras/doctest/CMakeLists.txt, extras/doctest/include/rapidcheck/doctest.h
This PR adds basic support for integration with the [doctest](https://github.com/doctest/doctest) library that follows the example laid out by the existing support for the Catch library.
The basic idea is to offer an alternate version of the `rc::check` function with similar semantics, but that reports its success or failure to the doctest test runner for inclusion in the statistics being gathered for the test run. This allows for deeper integration with IDE's such as VS code etc along the lines of JUNIT.
This initial implementation assumes compiler support for the `<source_location>` header in order to avoid the need for macros; if there is interest, however, I could probably extend this support for older compilers that do not yet support the `<source_location>` standard library header. …
=> Basic doctest integration

doc/gtest.md, examples/gtest/main.cpp, extras/gtest/include/rapidcheck/gtest.h
Hi! Would be nice to support type-parameterized properties with GoogleTest. I think this is probably the main annoyance that I face when trying to integrate RapidCheck with GoogleTest. In this PR I am implementing a macro to add such integration.
The small down-side I can think of this approach is that the test fixture will be instantiated one time too much (by the `TYPED_TEST` macro itself), but I think it should be a small overhead when the property is checked many times.
I cannot think of clean alternatives that play nice with GoogleTest, since the type list in the test suite is a private implementation detail, so a metaprogramming-based solution that manipulates the type list directly without using the `TYPED_TEST` macro sounds like a really bad idea.
Resolves #125
=> Add GTest type-parameterized fixture
